// user
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'

// plants
export const FETCH_PLANT = 'FETCH_PLANT'
export const FETCH_PLANT_SUCCESS = 'FETCH_PLANT_SUCCESS'
export const FETCH_PLANT_FAILURE = 'FETCH_PLANT_FAILURE'
export const FETCH_PLANTS = 'FETCH_PLANTS'
export const FETCH_PLANTS_SUCCESS = 'FETCH_PLANTS_SUCCESS'
export const FETCH_PLANTS_FAILURE = 'FETCH_PLANTS_FAILURE'
export const ADD_PLANT = 'ADD_PLANT'
export const REMOVE_PlANT = 'REMOVE_PlANT'
export const UPDATE_PLANT = 'UPDATE_PLANT'
export const REMOVE_PLANT = 'REMOVE_PLANT'

// comments
export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE'
export const ADD_COMMENT = 'ADD_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
